version: '3.8'

# Docker Compose for Testing MCP Server Integration
# This setup runs Ollama and tests in containers on the same network

services:
  # Ollama service for testing
  ollama:
    image: ollama/ollama:latest
    container_name: test-ollama
    ports:
      - "11435:11434"  # Map to different port to avoid conflict
    volumes:
      - ollama_test_data:/root/.ollama
    networks:
      - courtlistener_integration_net
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    # Use default Ollama startup and pull model after
    restart: unless-stopped

  # Test runner service  
  mcp-test-runner:
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: mcp-test-runner
    environment:
      - COURTLISTENER_API_TOKEN=${COURTLISTENER_API_TOKEN}
      - OLLAMA_HOST=http://ollama:11434
      - NODE_ENV=test
      - DOCKER_CONTAINER=true
    volumes:
      - ./tests:/app/tests
      - ./jest.config.cjs:/app/jest.config.cjs
      - ./tsconfig.test.json:/app/tsconfig.test.json
      - ./package.json:/app/package.json
    networks:
      - courtlistener_integration_net
    depends_on:
      ollama:
        condition: service_healthy
    # Keep container alive, run tests via script
    tty: true
    stdin_open: true
    command: ["bash", "-c", "while true; do sleep 30; done"]

networks:
  courtlistener_integration_net:
    external: true

volumes:
  ollama_test_data:
