version: '3.8'

services:
  # CourtListener MCP Server - Standalone
  courtlistener-mcp:
    image: ghcr.io/1trippycat/courtlistener-mcp:latest
    environment:
      - COURTLISTENER_API_TOKEN=${COURTLISTENER_API_TOKEN}
      - NODE_ENV=production
      - RATE_LIMIT_REQUESTS=100
      - RATE_LIMIT_WINDOW_MS=60000
      - REQUEST_TIMEOUT_MS=30000
    restart: unless-stopped
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mcp-network

  # Example: Integrate with your existing MCP client
  # your-mcp-client:
  #   image: your-client:latest
  #   environment:
  #     - MCP_SERVER_COMMAND=docker exec -i courtlistener-mcp node /app/build/index.js
  #   depends_on:
  #     - courtlistener-mcp
  #   networks:
  #     - mcp-network

networks:
  mcp-network:
    driver: bridge
