version: '3.8'

# Standalone CourtListener MCP Server
# Use this for basic MCP server functionality without Ollama integration

services:
  courtlistener-mcp:
    image: ghcr.io/1trippycat/courtlistener-mcp:latest
    container_name: courtlistener-mcp-standalone
    environment:
      - COURTLISTENER_API_TOKEN=${COURTLISTENER_API_TOKEN}
      - NODE_ENV=production
      - RATE_LIMIT_REQUESTS=${RATE_LIMIT_REQUESTS:-100}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - REQUEST_TIMEOUT_MS=${REQUEST_TIMEOUT_MS:-30000}
    restart: unless-stopped
    # Keep container alive for MCP connections
    tty: true
    stdin_open: true
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge
