version: '3.8'

services:
  courtlistener-mcp:
    image: ghcr.io/1trippycat/courtlistener-mcp:latest
    environment:
      - COURTLISTENER_API_TOKEN=${COURTLISTENER_API_TOKEN}
      - NODE_ENV=production
    restart: unless-stopped
    # Keep container alive for MCP connections
    tty: true
    stdin_open: true
    networks:
      - mcp-network

networks:
  mcp-network:
    external: true
